### ISSUE TITLE
Using docker volumes with certbot

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-PDFStats#5]
A thing I'm currently struggling with: trying to use volumes with the docker container (where the volumes contain the certbot certs, so we wouldn't have to use letsencrypt everytime we restart the container), results in those folders having uid 0 (i.e. root), and docker then refuses to build or deploy with those volumes, as it cannot access them.

From my understanding, the solution is to either:
* use a different user in the docker container when starting / using certbot, so the volumes are accessible by the lightsail user
* copy in and out the certs into the right places in the container build process (more manual, not as great having certs in the image?)

Not sure how approach either, couldn't find any specific online help for the issue

**Comment by nonprofittechy** [comment]
Docassemble's "fix" for this is to use S3 to store the lets-encrypt certs. I guess that adds several dependencies but it's not a crazy idea if the code is easy to grab from Docassemble's initialize.sh

**Comment by BryceStevenWilley** [comment]
I do think that S3 is overkill for this: the E-file proxy server [stores the certs in docker volumes](https://github.com/SuffolkLITLab/EfileProxyServer/blob/399662d611c17a9babd331edceae1a8af5bbb6d3/docker-compose.yml#L17-L18), and works fine. The issue is just the fact that we run as root in the dockerfile; it should be fixable, just needs some time tinkering with users in the image / container, and understanding where exactly nginx needs the certs.

 > note that we need this to work both locally (without https) and on the proper site. so something that is hardcoded in the dockerfile may not be great?
 
 This is also working fine in the [EfileProxyServer dockerfile](https://github.com/SuffolkLITLab/EfileProxyServer/blob/399662d611c17a9babd331edceae1a8af5bbb6d3/Dockerfile#L2-4): you can conditionally copy files into the image, or we can just adjust the startup script to look for certs in a specific folder before starting nginx.

**Comment by BryceStevenWilley** [comment]
Made some progress here in https://github.com/SuffolkLITLab/docassemble-PDFStats/commit/89f2a2deaa7302f63f490245f3739733f4c5b1a6 (deployed last night, but couldn't commit until now). Mostly that the docker volumes actually work; we don't need to re-certify with letsencrypt to re-deploy at all. It's still a bit to actually redeploy, since we need to update the nginx.conf still, so I won't close this quite yet. But we can at least play with things a lot easier now, since we won't be rate limited.
